#!/bin/bash
pwd
 0-current_working_directory
 ls -a
 chmod u+x 0-current_working_directory
 git config user.email zemikimechristopher@gmail.com
 git config user.name Naochrist
 git add
 git add .
  git commit -m 'working directory'
  git push
  